### ISSUE TITLE
Cortex Analyst Service - "No active warehouse selected in the current session." error

### ISSUE THREAD

**Issue by sfc-gh-pmanowiecki** [Snowflake-Labs/mcp#24]
For service defined in service_config as :

```
analyst_services:
  - service_name: "FESTIVAL_ANALYST"
    semantic_model: "@SNOWFLAKE_INTELLIGENCE.CONFIG.SEMANTIC_MODELS/music_festival.yaml"
    description: > # Should start with "Analyst service that ..."
      "Analyst service that returns data about a given festival"

```

MCP Tool called by Cursor with params:

```
{
  "query": "How many ticket sales were there for Difficult Fest?"
}
```

Effect:

Error calling tool 'FESTIVAL_ANALYST': 
000606 (57P03): No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

Screenshot from Cursor Agent with MCP installed:

<img width="662" alt="Image" src="https://github.com/user-attachments/assets/680deece-7bc3-4f35-aa86-6b71e138f801" />
